name: cec_dart
description: Dart library for sending and receiving HDMI CEC commands with libcec from Pulse-Eight.
version: 0.0.1
#author: Jacob Bang <julemand101@archlinux.dk>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  ccompile: "^0.2.10"
  logging: "^0.11.3+1"
  path: "^1.5.1"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
