part of cec_dart;

enum CEC_deck_info {
  CEC_DECK_INFO_PLAY,
  CEC_DECK_INFO_RECORD,
  CEC_DECK_INFO_PLAY_REVERSE,
  CEC_DECK_INFO_STILL,
  CEC_DECK_INFO_SLOW,
  CEC_DECK_INFO_SLOW_REVERSE,
  CEC_DECK_INFO_FAST_FORWARD,
  CEC_DECK_INFO_FAST_REVERSE,
  CEC_DECK_INFO_NO_MEDIA,
  CEC_DECK_INFO_STOP,
  CEC_DECK_INFO_SKIP_FORWARD_WIND,
  CEC_DECK_INFO_SKIP_REVERSE_REWIND,
  CEC_DECK_INFO_INDEX_SEARCH_FORWARD,
  CEC_DECK_INFO_INDEX_SEARCH_REVERSE,
  CEC_DECK_INFO_OTHER_STATUS,
  CEC_DECK_INFO_OTHER_STATUS_LG,
}

class _CEC_deck_info {
  static Map<CEC_deck_info, int> toValue = {
    CEC_deck_info.CEC_DECK_INFO_PLAY: 0x11,
    CEC_deck_info.CEC_DECK_INFO_RECORD: 0x12,
    CEC_deck_info.CEC_DECK_INFO_PLAY_REVERSE: 0x13,
    CEC_deck_info.CEC_DECK_INFO_STILL: 0x14,
    CEC_deck_info.CEC_DECK_INFO_SLOW: 0x15,
    CEC_deck_info.CEC_DECK_INFO_SLOW_REVERSE: 0x16,
    CEC_deck_info.CEC_DECK_INFO_FAST_FORWARD: 0x17,
    CEC_deck_info.CEC_DECK_INFO_FAST_REVERSE: 0x18,
    CEC_deck_info.CEC_DECK_INFO_NO_MEDIA: 0x19,
    CEC_deck_info.CEC_DECK_INFO_STOP: 0x1A,
    CEC_deck_info.CEC_DECK_INFO_SKIP_FORWARD_WIND: 0x1B,
    CEC_deck_info.CEC_DECK_INFO_SKIP_REVERSE_REWIND: 0x1C,
    CEC_deck_info.CEC_DECK_INFO_INDEX_SEARCH_FORWARD: 0x1D,
    CEC_deck_info.CEC_DECK_INFO_INDEX_SEARCH_REVERSE: 0x1E,
    CEC_deck_info.CEC_DECK_INFO_OTHER_STATUS: 0x1F,
    CEC_deck_info.CEC_DECK_INFO_OTHER_STATUS_LG: 0x20,
  };
  static Map<int, CEC_deck_info> toEnum =
      new Map.fromIterables(toValue.values, toValue.keys);
}
