part of cec_dart;

enum CEC_play_mode {
  CEC_PLAY_MODE_PLAY_FORWARD,
  CEC_PLAY_MODE_PLAY_REVERSE,
  CEC_PLAY_MODE_PLAY_STILL,
  CEC_PLAY_MODE_FAST_FORWARD_MIN_SPEED,
  CEC_PLAY_MODE_FAST_FORWARD_MEDIUM_SPEED,
  CEC_PLAY_MODE_FAST_FORWARD_MAX_SPEED,
  CEC_PLAY_MODE_FAST_REVERSE_MIN_SPEED,
  CEC_PLAY_MODE_FAST_REVERSE_MEDIUM_SPEED,
  CEC_PLAY_MODE_FAST_REVERSE_MAX_SPEED,
  CEC_PLAY_MODE_SLOW_FORWARD_MIN_SPEED,
  CEC_PLAY_MODE_SLOW_FORWARD_MEDIUM_SPEED,
  CEC_PLAY_MODE_SLOW_FORWARD_MAX_SPEED,
  CEC_PLAY_MODE_SLOW_REVERSE_MIN_SPEED,
  CEC_PLAY_MODE_SLOW_REVERSE_MEDIUM_SPEED,
  CEC_PLAY_MODE_SLOW_REVERSE_MAX_SPEED,
}

class _CEC_play_mode {
  static Map<CEC_play_mode, int> toValue = {
    CEC_play_mode.CEC_PLAY_MODE_PLAY_FORWARD: 0x24,
    CEC_play_mode.CEC_PLAY_MODE_PLAY_REVERSE: 0x20,
    CEC_play_mode.CEC_PLAY_MODE_PLAY_STILL: 0x25,
    CEC_play_mode.CEC_PLAY_MODE_FAST_FORWARD_MIN_SPEED: 0x05,
    CEC_play_mode.CEC_PLAY_MODE_FAST_FORWARD_MEDIUM_SPEED: 0x06,
    CEC_play_mode.CEC_PLAY_MODE_FAST_FORWARD_MAX_SPEED: 0x07,
    CEC_play_mode.CEC_PLAY_MODE_FAST_REVERSE_MIN_SPEED: 0x09,
    CEC_play_mode.CEC_PLAY_MODE_FAST_REVERSE_MEDIUM_SPEED: 0x0A,
    CEC_play_mode.CEC_PLAY_MODE_FAST_REVERSE_MAX_SPEED: 0x0B,
    CEC_play_mode.CEC_PLAY_MODE_SLOW_FORWARD_MIN_SPEED: 0x15,
    CEC_play_mode.CEC_PLAY_MODE_SLOW_FORWARD_MEDIUM_SPEED: 0x16,
    CEC_play_mode.CEC_PLAY_MODE_SLOW_FORWARD_MAX_SPEED: 0x17,
    CEC_play_mode.CEC_PLAY_MODE_SLOW_REVERSE_MIN_SPEED: 0x19,
    CEC_play_mode.CEC_PLAY_MODE_SLOW_REVERSE_MEDIUM_SPEED: 0x1A,
    CEC_play_mode.CEC_PLAY_MODE_SLOW_REVERSE_MAX_SPEED: 0x1B,
  };
  static Map<int, CEC_play_mode> toEnum =
      new Map.fromIterables(toValue.values, toValue.keys);
}
