part of cec_dart;

enum CEC_record_status_info {
  CEC_RECORD_STATUS_INFO_RECORDING_CURRENTLY_SELECTED_SOURCE,
  CEC_RECORD_STATUS_INFO_RECORDING_DIGITAL_SERVICE,
  CEC_RECORD_STATUS_INFO_RECORDING_ANALOGUE_SERVICE,
  CEC_RECORD_STATUS_INFO_RECORDING_EXTERNAL_INPUT,
  CEC_RECORD_STATUS_INFO_NO_RECORDING_UNABLE_TO_RECORD_DIGITAL_SERVICE,
  CEC_RECORD_STATUS_INFO_NO_RECORDING_UNABLE_TO_RECORD_ANALOGUE_SERVICE,
  CEC_RECORD_STATUS_INFO_NO_RECORDING_UNABLE_TO_SELECT_REQUIRED_SERVICE,
  CEC_RECORD_STATUS_INFO_NO_RECORDING_INVALID_EXTERNAL_PLUG_NUMBER,
  CEC_RECORD_STATUS_INFO_NO_RECORDING_INVALID_EXTERNAL_ADDRESS,
  CEC_RECORD_STATUS_INFO_NO_RECORDING_CA_SYSTEM_NOT_SUPPORTED,
  CEC_RECORD_STATUS_INFO_NO_RECORDING_NO_OR_INSUFFICIENT_ENTITLEMENTS,
  CEC_RECORD_STATUS_INFO_NO_RECORDING_NOT_ALLOWED_TO_COPY_SOURCE,
  CEC_RECORD_STATUS_INFO_NO_RECORDING_NO_FURTHER_COPIES_ALLOWED,
  CEC_RECORD_STATUS_INFO_NO_RECORDING_NO_MEDIA,
  CEC_RECORD_STATUS_INFO_NO_RECORDING_PLAYING,
  CEC_RECORD_STATUS_INFO_NO_RECORDING_ALREADY_RECORDING,
  CEC_RECORD_STATUS_INFO_NO_RECORDING_MEDIA_PROTECTED,
  CEC_RECORD_STATUS_INFO_NO_RECORDING_NO_SOURCE_SIGNAL,
  CEC_RECORD_STATUS_INFO_NO_RECORDING_MEDIA_PROBLEM,
  CEC_RECORD_STATUS_INFO_NO_RECORDING_NOT_ENOUGH_SPACE_AVAILABLE,
  CEC_RECORD_STATUS_INFO_NO_RECORDING_PARENTAL_LOCK_ON,
  CEC_RECORD_STATUS_INFO_RECORDING_TERMINATED_NORMALLY,
  CEC_RECORD_STATUS_INFO_RECORDING_HAS_ALREADY_TERMINATED,
  CEC_RECORD_STATUS_INFO_NO_RECORDING_OTHER_REASON,
}

class _CEC_record_status_info {
  static Map<CEC_record_status_info, int> toValue = {
    CEC_record_status_info
        .CEC_RECORD_STATUS_INFO_RECORDING_CURRENTLY_SELECTED_SOURCE: 0x01,
    CEC_record_status_info.CEC_RECORD_STATUS_INFO_RECORDING_DIGITAL_SERVICE:
        0x02,
    CEC_record_status_info.CEC_RECORD_STATUS_INFO_RECORDING_ANALOGUE_SERVICE:
        0x03,
    CEC_record_status_info.CEC_RECORD_STATUS_INFO_RECORDING_EXTERNAL_INPUT:
        0x04,
    CEC_record_status_info
            .CEC_RECORD_STATUS_INFO_NO_RECORDING_UNABLE_TO_RECORD_DIGITAL_SERVICE:
        0x05,
    CEC_record_status_info
            .CEC_RECORD_STATUS_INFO_NO_RECORDING_UNABLE_TO_RECORD_ANALOGUE_SERVICE:
        0x06,
    CEC_record_status_info
            .CEC_RECORD_STATUS_INFO_NO_RECORDING_UNABLE_TO_SELECT_REQUIRED_SERVICE:
        0x07,
    CEC_record_status_info
        .CEC_RECORD_STATUS_INFO_NO_RECORDING_INVALID_EXTERNAL_PLUG_NUMBER: 0x09,
    CEC_record_status_info
        .CEC_RECORD_STATUS_INFO_NO_RECORDING_INVALID_EXTERNAL_ADDRESS: 0x0A,
    CEC_record_status_info
        .CEC_RECORD_STATUS_INFO_NO_RECORDING_CA_SYSTEM_NOT_SUPPORTED: 0x0B,
    CEC_record_status_info
            .CEC_RECORD_STATUS_INFO_NO_RECORDING_NO_OR_INSUFFICIENT_ENTITLEMENTS:
        0x0C,
    CEC_record_status_info
        .CEC_RECORD_STATUS_INFO_NO_RECORDING_NOT_ALLOWED_TO_COPY_SOURCE: 0x0D,
    CEC_record_status_info
        .CEC_RECORD_STATUS_INFO_NO_RECORDING_NO_FURTHER_COPIES_ALLOWED: 0x0E,
    CEC_record_status_info.CEC_RECORD_STATUS_INFO_NO_RECORDING_NO_MEDIA: 0x10,
    CEC_record_status_info.CEC_RECORD_STATUS_INFO_NO_RECORDING_PLAYING: 0x11,
    CEC_record_status_info
        .CEC_RECORD_STATUS_INFO_NO_RECORDING_ALREADY_RECORDING: 0x12,
    CEC_record_status_info.CEC_RECORD_STATUS_INFO_NO_RECORDING_MEDIA_PROTECTED:
        0x13,
    CEC_record_status_info.CEC_RECORD_STATUS_INFO_NO_RECORDING_NO_SOURCE_SIGNAL:
        0x14,
    CEC_record_status_info.CEC_RECORD_STATUS_INFO_NO_RECORDING_MEDIA_PROBLEM:
        0x15,
    CEC_record_status_info
        .CEC_RECORD_STATUS_INFO_NO_RECORDING_NOT_ENOUGH_SPACE_AVAILABLE: 0x16,
    CEC_record_status_info.CEC_RECORD_STATUS_INFO_NO_RECORDING_PARENTAL_LOCK_ON:
        0x17,
    CEC_record_status_info.CEC_RECORD_STATUS_INFO_RECORDING_TERMINATED_NORMALLY:
        0x1A,
    CEC_record_status_info
        .CEC_RECORD_STATUS_INFO_RECORDING_HAS_ALREADY_TERMINATED: 0x1B,
    CEC_record_status_info.CEC_RECORD_STATUS_INFO_NO_RECORDING_OTHER_REASON:
        0x1F,
  };
  static Map<int, CEC_record_status_info> toEnum =
      new Map.fromIterables(toValue.values, toValue.keys);
}
